'use strict';

const USER_ROLES = {
  ADMIN: 'ADMIN',
  PSICOPEDAGOGO: 'PSICOPEDAGOGO',
  VIEWER: 'VIEWER',
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

const SEXO = {
  MASCULINO: 'MASCULINO',
  FEMININO: 'FEMININO',
  OUTRO: 'OUTRO',
};

const AVALIACAO_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
};

const QUESTION_TYPES = {
  TEXT: 'TEXT',
  LONG_TEXT: 'LONG_TEXT',
  NUMERIC: 'NUMERIC',
  DATE: 'DATE',
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  SCALE: 'SCALE',
  YES_NO: 'YES_NO',
};

const APLICACAO_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  SEXO,
  AVALIACAO_STATUS,
  QUESTION_TYPES,
  APLICACAO_STATUS,
};
